# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "MahewinSimpleBlog"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

plugins:
  MahewinSimpleBlog::Configuration:
    blog_name: "Hobbestigrou"
    subtitle: "Just another Perl hacker"
    articles_directory: "articles"
    comments_directory: "comments"
    theme_highlight_code: "default"
    #Feed format can be atom or rss, default is rss
    format_feed: "rss"
    articles_per_feed: 10
    articles_per_page: 5
    footer: 'Powered by <a href="http://perldancer.org">Dancer</a> and MahewinSimpleBlog'
